Repository ace-ecosystem/ace2-ams, pull requests merged in 2022-04, with the labels that each got.

#176 Update reset filters button
  frontend/src/components/Filters/TheFilterToolbar.vue
  frontend/src/stores/helpers.ts
  frontend/tests/e2e/specs/ManageEvents.spec.js
  frontend/tests/unit/src/store/helpers.spec.ts
Labels: enhancement, gui

#177 GUI - Event Details - Sandbox Summary
  frontend/src/components/Analysis/SandboxAnalysis.vue
  frontend/src/components/Events/TheEventDetailsMenuBar.vue
  frontend/src/etc/configuration/analysis.ts
  frontend/src/etc/configuration/test/analysis.ts
  frontend/src/pages/Events/ViewEvent.vue
  frontend/src/services/api/event.ts
  frontend/tests/component/src/components/Analysis/SandboxAnalysis.spec.ts
  frontend/tests/e2e/specs/ViewEvent.spec.js
  frontend/tests/unit/src/services/api/event.spec.ts
Labels: enhancement, gui

#178 Add more component tests
  docs/development/frontend/testing.md
  docs/development/index.md
  frontend/src/components/Alerts/AlertTree.vue
  frontend/src/components/Alerts/TheAlertActionToolbar.vue
  frontend/src/components/Alerts/TheAlertDetails.vue
  frontend/src/components/Alerts/TheAlertsTable.vue
  frontend/src/components/Analysis/EmailAnalysis.vue
  frontend/src/components/Analysis/EmailAnalysisHeadersBody.vue
  frontend/src/components/Analysis/EmailAnalysisSummaryTable.vue
  frontend/src/components/Analysis/UserAnalysis.vue
  frontend/src/components/Events/EventAlertsTable.vue
  frontend/src/services/api/event.ts
  frontend/tests/component/src/components/Alerts/TheAlertActionToolbar.spec.ts
  frontend/tests/component/src/components/Alerts/TheAlertDetails.spec.ts
  frontend/tests/component/src/components/Alerts/TheAlertsTable.spec.ts
  frontend/tests/component/src/components/Analysis/AnalysisDetailsBase.spec.ts
  frontend/tests/component/src/components/Analysis/EmailAnalysis.spec.ts
  frontend/tests/component/src/components/Analysis/EmailAnalysisHeadersBody.spec.ts
  frontend/tests/component/src/components/Analysis/EmailAnalysisSummaryTable.spec.ts
  frontend/tests/component/src/components/Analysis/UserAnalysis.spec.ts
  frontend/tests/component/src/components/Events/EventAlertsTable.spec.ts
  frontend/tests/e2e/specs/TheAlertsTable.spec.js
  frontend/tests/unit/src/components/Alerts/TheAlertActionToolbar.spec.ts.old
  frontend/tests/unit/src/components/Alerts/TheAlertDetails.spec.ts.old
  frontend/tests/unit/src/components/Alerts/TheAlertsTable.spec.ts.old
  frontend/tests/unit/src/components/Events/EventAlertsTable.spec.ts.old
Labels: refactor, gui

#179 Edit Event Bugfix
  frontend/src/components/Modals/EditEventModal.vue
  frontend/src/components/Node/NodePropertyInput.vue
  frontend/src/etc/helpers.ts
  frontend/src/models/event.ts
  frontend/tests/component/src/components/Modals/EditEventModal.spec.ts
  frontend/tests/mocks/genericObject.ts
Labels: bug, gui

#181 Updates docs after splitting the APIs
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  docker-compose.yml
  docs/development/backend/database.md
  docs/development/backend/environment_variables.md
  docs/development/backend/insert_alerts.md
  docs/development/index.md
  docs/index.md
Labels: documentation

#183 More Component Tests
  frontend/src/components/Events/EventDetectionsSummary.vue
  frontend/src/components/Events/EventObservableSummary.vue
  frontend/src/components/Events/EventSummary.vue
  frontend/src/components/Events/EventTableCell.vue
  frontend/src/components/Events/EventURLDomainSummary.vue
  frontend/src/components/Events/EventURLSummary.vue
  frontend/src/components/Events/TheEventDetailsMenuBar.vue
  frontend/src/components/Events/TheEventsTable.vue
  frontend/src/components/Modals/AssignModal.vue
  frontend/src/components/Modals/BaseModal.vue
  frontend/src/components/Modals/CommentModal.vue
  frontend/src/models/event.ts
  frontend/src/models/eventSummaries.ts
  frontend/src/services/api/event.ts
  frontend/tests/component/src/components/Alerts/AlertTree.spec.ts
  frontend/tests/component/src/components/Alerts/AnalyzeAlertForm.spec.ts
  frontend/tests/component/src/components/Alerts/TheAlertActionToolbar.spec.ts
  frontend/tests/component/src/components/Alerts/TheAlertDetails.spec.ts
  frontend/tests/component/src/components/Alerts/TheAlertsTable.spec.ts
  frontend/tests/component/src/components/Analysis/AnalysisDetailsBase.spec.ts
  frontend/tests/component/src/components/Analysis/EmailAnalysis.spec.ts
  frontend/tests/component/src/components/Analysis/EmailAnalysisHeadersBody.spec.ts
  frontend/tests/component/src/components/Analysis/EmailAnalysisSummaryTable.spec.ts
  frontend/tests/component/src/components/Analysis/SandboxAnalysis.spec.ts
  frontend/tests/component/src/components/Analysis/UserAnalysis.spec.ts
  frontend/tests/component/src/components/Events/EventDetectionsSummary.spec.ts
  frontend/tests/component/src/components/Events/EventObservableSummary.spec.ts
  frontend/tests/component/src/components/Events/EventSummary.spec.ts
  frontend/tests/component/src/components/Events/EventTableCell.spec.ts
  frontend/tests/component/src/components/Events/EventURLDomainSummary.spec.ts
  frontend/tests/component/src/components/Events/EventURLSummary.spec.ts
  frontend/tests/component/src/components/Events/TheEventDetailsMenuBar.spec.ts
  frontend/tests/component/src/components/Events/TheEventsTable.spec.ts
  frontend/tests/component/src/components/Modals/AssignModal.spec.ts
  frontend/tests/component/src/components/Modals/BaseModal.spec.ts
  frontend/tests/component/src/components/Modals/CommentModal.spec.ts
  frontend/tests/component/src/components/Modals/DeleteModal.spec.ts
  frontend/tests/component/src/components/Modals/RemediateModal.spec.ts
  frontend/tests/e2e/support/commands.js
Labels: refactor, gui

#185 Analysis caching
  api_models/analysis.py
  api_models/analysis_module_type.py
  db_api/app/api/routes/analysis.py
  db_api/app/api/routes/analysis_module_type.py
  db_api/app/db/crud/__init__.py
  db_api/app/db/migrations/versions/efd69a6a8274_initial.py
  db_api/app/db/schemas/analysis.py
  db_api/app/db/schemas/analysis_module_type.py
  db_api/app/tests/api/analysis/test_create.py
  db_api/app/tests/api/analysis/test_read.py
  db_api/app/tests/api/analysis/test_update.py
  db_api/app/tests/api/analysis_module_type/test_create.py
  db_api/app/tests/api/analysis_module_type/test_update.py
  db_api/app/tests/api/event/test_read.py
  db_api/app/tests/api/node/test_read.py
  db_api/app/tests/api/node_relationship/test_create.py
  db_api/app/tests/api/node_relationship/test_delete.py
  db_api/app/tests/api/node_tree/test_read.py
  db_api/app/tests/api/observable/test_read.py
  db_api/app/tests/helpers.py
  frontend/src/models/analysis.ts
  frontend/src/models/analysisModuleType.ts
  frontend/tests/mocks/analysis.ts
  frontend/tests/unit/src/services/api/analysis.spec.ts
  gui_api/app/tests/api/analysis/test_read.py
Labels: enhancement, api

#186 Analysis caching exclusion constraint
  db_api/app/api/routes/analysis.py
  db_api/app/db/crud/__init__.py
  db_api/app/db/migrations/versions/cbfc69c2e753_initial.py
  db_api/app/db/schemas/analysis.py
  db_api/app/tests/alerts/smallWithUrls.json
  db_api/app/tests/api/analysis/test_create.py
  db_api/app/tests/api/event/test_read.py
  db_api/app/tests/helpers.py
  db_container/extensions.sh
  frontend/tests/e2e/specs/ViewAlert.spec.js
Labels: enhancement, api

#184 Initial Observable Actions
  frontend/src/components/Alerts/AlertTree.vue
  frontend/src/components/Observables/ObservableActions/UpdateDetectionExpiration.vue
  frontend/src/components/Observables/ObservableLeaf.vue
  frontend/src/etc/configuration/index.ts
  frontend/src/etc/configuration/observables.ts
  frontend/src/etc/configuration/test/index.ts
  frontend/src/etc/configuration/test/observables.ts
  frontend/src/etc/constants/observables.ts
  frontend/src/main.ts
  frontend/src/models/observable.ts
  frontend/src/models/observableType.ts
  frontend/tests/component/src/components/Alerts/AlertTree.spec.ts
  frontend/tests/component/src/components/Observables/ObservableActions/UpdateDetectionExpiration.spec.ts
  frontend/tests/component/src/components/Observables/ObservableLeaf.spec.ts
  frontend/tests/e2e/specs/ViewAlert.spec.js
Labels: enhancement, gui

#187 Analysis child observables
  api_models/analysis.py
  api_models/observable.py
  db_api/app/api/routes/analysis.py
  db_api/app/db/crud/observable.py
  db_api/app/db/crud/observable_type.py
  db_api/app/db/migrations/versions/5f818dc4ffb9_initial.py
  db_api/app/db/schemas/__init__.py
  db_api/app/db/schemas/analysis.py
  db_api/app/db/schemas/analysis_child_observable_mapping.py
  db_api/app/tests/api/analysis/test_create.py
  frontend/src/models/analysis.ts
  frontend/tests/mocks/analysis.ts
  gui_api/app/tests/api/analysis/test_read.py
Labels: enhancement, api

#188 Does not automatically create observable type when creating observable
  db_api/app/db/crud/observable.py
  db_api/app/db/crud/observable_type.py
  db_api/app/tests/api/analysis/test_create.py
  db_api/app/tests/db/observable.py
Labels: api
