Repository ace-ecosystem/ace2-ams, pull requests merged in 2022-06, with the labels that each got.

#250 Fix NodePropertyInput bug
  frontend/src/components/Node/NodePropertyInput.vue
  frontend/tests/component/src/components/Node/NodePropertyInput.spec.ts
Labels: bug, gui, critical

#251 Upgrade to Cypress v10
  .github/workflows/main.yml
  .gitignore
  bin/test-components.sh
  bin/test-e2e.sh
  docs/development/index.md
  frontend/Dockerfile.dev
  frontend/cypress.config.ts
  frontend/cypress.json
  frontend/cypress/support/component-index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/tests/e2e/plugins/index.js
  frontend/tests/e2e/specs/ViewEvent.spec.js
Labels: gui

#252 Analysis Details Base
  frontend/src/components/Analysis/AnalysisDetailsBase.vue
  frontend/src/components/test/TestComponent.vue
  frontend/src/etc/configuration/test/analysis.ts
  frontend/src/pages/Analysis/ViewAnalysis.vue
  frontend/src/router/index.ts
  frontend/tests/component/src/components/Analysis/AnalysisDetailsBase.spec.ts
  frontend/tests/component/src/pages/Alerts/ViewAnalysis.spec.ts
  frontend/tests/component/src/pages/Analysis/ViewAnalysis.spec.ts
Labels: enhancement, gui

#254 Add Observable Button
  api_models/submission.py
  docs/development/frontend/testing.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Alerts/AnalyzeAlertForm.vue
  frontend/src/components/Alerts/TheAlertActionToolbar.vue
  frontend/src/components/Modals/AddObservablesModal.vue
  frontend/src/components/Observables/NewObservableForm.vue
  frontend/src/components/Observables/ObservableInput.vue
  frontend/src/models/alert.ts
  frontend/src/services/api/observable.ts
  frontend/tests/component/src/components/Alerts/AnalyzeAlertForm.spec.ts
  frontend/tests/component/src/components/Alerts/TheAlertActionToolbar.spec.ts
  frontend/tests/component/src/components/Modals/AddObservablesModal.spec.ts
  frontend/tests/component/src/components/Observables/NewObservableForm.spec.ts
  frontend/tests/e2e/specs/ViewAlert.spec.js
  frontend/tests/mocks/alert.ts
  gui_api/app/api/routes/observable.py
  gui_api/app/tests/api/observable/test_create.py
Labels: enhancement, gui, api

#255 Close Event
  frontend/src/components/Events/TheEventDetailsMenuBar.vue
  frontend/src/etc/configuration/events.ts
  frontend/src/etc/configuration/test/events.ts
  frontend/src/pages/Events/ViewEvent.vue
  frontend/tests/component/src/components/Events/TheEventDetailsMenuBar.spec.ts
Labels: enhancement, gui

#256 Refactor/breakout multialert button
  frontend/src/components/Alerts/AnalyzeAlertForm.vue
  frontend/src/components/Observables/NewObservableForm.vue
  frontend/tests/component/src/components/Alerts/AnalyzeAlertForm.spec.ts
  frontend/tests/component/src/pages/Alerts/AnalyzeAlert.spec.ts
  frontend/tests/e2e/specs/AnalyzeAlert.spec.js
Labels: enhancement, gui

#257 Hide TheHeader links/icons when not auth'd
  frontend/src/components/UserInterface/TheHeader.vue
  frontend/tests/component/src/components/UserInterface/TheHeader.spec.ts
  frontend/tests/e2e/specs/ManageAlerts.spec.js
Labels: bug, gui

#262 Analysis metadata (Part 2 - observable display type/value)
  api_models/metadata_display_type.py
  api_models/metadata_display_value.py
  api_models/observable.py
  db_api/app/api/routes/__init__.py
  db_api/app/api/routes/metadata_display_type.py
  db_api/app/api/routes/metadata_display_value.py
  db_api/app/db/crud/__init__.py
  db_api/app/db/crud/analysis_metadata.py
  db_api/app/db/crud/metadata_display_type.py
  db_api/app/db/crud/metadata_display_value.py
  db_api/app/db/crud/observable.py
  db_api/app/db/crud/submission.py
  db_api/app/db/migrations/versions/f494a9e8f48c_initial.py
  db_api/app/db/schemas/__init__.py
  db_api/app/db/schemas/metadata_display_type.py
  db_api/app/db/schemas/metadata_display_value.py
  db_api/app/db/schemas/observable.py
  db_api/app/tests/alerts/small.json
  db_api/app/tests/api_tests/metadata_display_type/__init__.py
  db_api/app/tests/api_tests/metadata_display_type/test_create.py
  db_api/app/tests/api_tests/metadata_display_type/test_delete.py
  db_api/app/tests/api_tests/metadata_display_type/test_read.py
  db_api/app/tests/api_tests/metadata_display_type/test_update.py
  db_api/app/tests/api_tests/metadata_display_value/__init__.py
  db_api/app/tests/api_tests/metadata_display_value/test_create.py
  db_api/app/tests/api_tests/metadata_display_value/test_delete.py
  db_api/app/tests/api_tests/metadata_display_value/test_read.py
  db_api/app/tests/api_tests/metadata_display_value/test_update.py
  db_api/app/tests/db_tests/crud/metadata_display_type/__init__.py
  db_api/app/tests/db_tests/crud/metadata_display_type/test_create.py
  db_api/app/tests/db_tests/crud/metadata_display_type/test_delete.py
  db_api/app/tests/db_tests/crud/metadata_display_type/test_read.py
  db_api/app/tests/db_tests/crud/metadata_display_type/test_update.py
  db_api/app/tests/db_tests/crud/metadata_display_value/__init__.py
  db_api/app/tests/db_tests/crud/metadata_display_value/test_create.py
  db_api/app/tests/db_tests/crud/metadata_display_value/test_delete.py
  db_api/app/tests/db_tests/crud/metadata_display_value/test_read.py
  db_api/app/tests/db_tests/crud/metadata_display_value/test_update.py
  db_api/app/tests/db_tests/crud/submission/test_read.py
  db_api/app/tests/factory/__init__.py
  db_api/app/tests/factory/metadata_display_type.py
  db_api/app/tests/factory/metadata_display_value.py
  db_api/app/tests/factory/observable.py
  frontend/src/components/Observables/ObservableLeaf.vue
  frontend/src/models/metadataDisplayType.ts
  frontend/src/models/metadataDisplayValue.ts
  frontend/src/models/observable.ts
  frontend/tests/component/src/components/Observables/ObservableLeaf.spec.ts
  frontend/tests/mocks/observable.ts
Labels: enhancement, gui, api

#263 Explicity "None" filters
  db_api/app/db/crud/event.py
  db_api/app/db/crud/submission.py
  db_api/app/tests/db_tests/crud/event/test_read.py
  db_api/app/tests/db_tests/crud/submission/test_read.py
  frontend/src/components/Node/NodePropertyInput.vue
  frontend/src/etc/constants/alerts.ts
  frontend/src/etc/constants/common.ts
  frontend/src/models/base.ts
  frontend/tests/component/src/components/Filters/TheFilterToolbar.spec.ts
  frontend/tests/component/src/components/Node/NodePropertyInput.spec.ts
  frontend/tests/e2e/specs/ManageAlerts.spec.js
Labels: enhancement, gui, api

#264 Analysis metadata (refactor)
  api_models/analysis_metadata.py
  api_models/observable.py
  api_models/submission.py
  db_api/app/db/crud/analysis_metadata.py
  db_api/app/db/crud/submission.py
  db_api/app/db/schemas/analysis.py
  db_api/app/db/schemas/metadata.py
  db_api/app/db/schemas/metadata_display_type.py
  db_api/app/db/schemas/metadata_display_value.py
  db_api/app/db/schemas/metadata_tag.py
  db_api/app/db/schemas/observable.py
  db_api/app/db/schemas/submission.py
  db_api/app/tests/db_tests/crud/analysis_metadata/test_create.py
  db_api/app/tests/db_tests/crud/event/test_read.py
  db_api/app/tests/db_tests/crud/submission/test_create.py
  db_api/app/tests/db_tests/crud/submission/test_read.py
  frontend/src/components/Alerts/AlertTableExpansion.vue
  frontend/src/components/Events/EventObservableSummary.vue
  frontend/src/components/Observables/ObservableLeaf.vue
  frontend/src/models/analysisMetadata.ts
  frontend/src/models/observable.ts
  frontend/tests/component/src/components/Alerts/AlertTableExpansion.spec.ts
  frontend/tests/component/src/components/Alerts/TheAlertsTable.spec.ts
  frontend/tests/component/src/components/Observables/ObservableLeaf.spec.ts
  frontend/tests/mocks/analysisMetadata.ts
  frontend/tests/mocks/observable.ts
  gui_api/app/tests/api/alert/test_read.py
Labels: refactor, api

#265 Disposition History (backend changes)
  api_models/observable.py
  db_api/app/db/crud/submission.py
  db_api/app/db/schemas/observable.py
  db_api/app/tests/db_tests/crud/submission/test_read.py
  frontend/src/models/observable.ts
  frontend/tests/mocks/dispositionHistory.ts
  frontend/tests/mocks/observable.ts
Labels: enhancement, api

#268 Renames the permanent_tags fields on observables to just tags
  api_models/observable.py
  api_models/submission.py
  db_api/app/db/crud/event.py
  db_api/app/db/crud/observable.py
  db_api/app/db/crud/submission.py
  db_api/app/db/migrations/versions/8ecf40aa22be_initial.py
  db_api/app/db/schemas/__init__.py
  db_api/app/db/schemas/observable.py
  db_api/app/db/schemas/observable_tag_mapping.py
  db_api/app/db/schemas/submission.py
  db_api/app/tests/alerts/small.json
  db_api/app/tests/alerts/small_template.json
  db_api/app/tests/api_tests/observable/test_create.py
  db_api/app/tests/api_tests/observable/test_update.py
  db_api/app/tests/db_tests/crud/event/test_read.py
  db_api/app/tests/db_tests/crud/observable/test_create.py
  db_api/app/tests/db_tests/crud/observable/test_update.py
  db_api/app/tests/db_tests/crud/submission/test_create.py
  db_api/app/tests/db_tests/crud/submission/test_read.py
  db_api/app/tests/factory/observable.py
  db_api/app/tests/factory/submission.py
  frontend/src/components/Alerts/AlertTableExpansion.vue
  frontend/src/components/Events/EventObservableSummary.vue
  frontend/src/components/Modals/RemoveTagModal.vue
  frontend/src/components/Modals/TagModal.vue
  frontend/src/components/Observables/ObservableLeaf.vue
  frontend/src/etc/helpers.ts
  frontend/src/models/alert.ts
  frontend/src/models/observable.ts
  frontend/tests/component/src/components/Alerts/AlertTableExpansion.spec.ts
  frontend/tests/component/src/components/Alerts/AlertTree.spec.ts
  frontend/tests/component/src/components/Events/EventObservableSummary.spec.ts
  frontend/tests/component/src/components/Modals/RemoveTagModal.spec.ts
  frontend/tests/component/src/components/Modals/TagModal.spec.ts
  frontend/tests/component/src/components/Observables/ObservableLeaf.spec.ts
  frontend/tests/mocks/alert.ts
  frontend/tests/mocks/observable.ts
  gui_api/app/tests/api/alert/test_read.py
  gui_api/app/tests/api/observable/test_read.py
Labels: refactor, gui, api

#269 OR Filtering
  db_api/app/api/routes/event.py
  db_api/app/api/routes/submission.py
  db_api/app/db/crud/event.py
  db_api/app/db/crud/submission.py
  db_api/app/tests/api_tests/event/test_read.py
  db_api/app/tests/api_tests/submission/test_read.py
  db_api/app/tests/db_tests/crud/event/test_read.py
  db_api/app/tests/db_tests/crud/submission/test_read.py
  frontend/src/components/Alerts/AlertTableExpansion.vue
  frontend/src/components/Events/EventAlertsTable.vue
  frontend/src/components/Filters/FilterChip.vue
  frontend/src/components/Filters/TheFilterToolbar.vue
  frontend/src/components/Metadata/MetadataTag.vue
  frontend/src/components/Modals/FilterModal.vue
  frontend/src/components/Modals/SaveToEventModal.vue
  frontend/src/components/Node/NodePropertyInput.vue
  frontend/src/components/Node/NodeQueueSelector.vue
  frontend/src/components/Observables/ObservableLeaf.vue
  frontend/src/components/UserInterface/DateRangePicker.vue
  frontend/src/etc/helpers.ts
  frontend/src/models/alert.ts
  frontend/src/models/event.ts
  frontend/src/services/api/base.ts
  frontend/src/stores/filter.ts
  frontend/tests/component/src/components/Alerts/AlertTableExpansion.spec.ts
  frontend/tests/component/src/components/Filters/FilterChip.spec.ts
  frontend/tests/component/src/components/Filters/FilterChipContainer.spec.ts
  frontend/tests/component/src/components/Filters/TheFilterToolbar.spec.ts
  frontend/tests/component/src/components/Metadata/Tag.spec.ts
  frontend/tests/component/src/components/Modals/FilterModal.spec.ts
  frontend/tests/component/src/components/Modals/SaveToEventModal.spec.ts
  frontend/tests/component/src/components/Observables/ObservableLeaf.spec.ts
  frontend/tests/component/src/components/UserInterface/DateRangePicker.spec.ts
  frontend/tests/e2e/specs/ManageAlerts.spec.js
  frontend/tests/e2e/specs/ManageEvents.spec.js
  frontend/tests/e2e/specs/TheEventsTable.spec.js
  frontend/tests/unit/src/etc/helpers.spec.ts
  frontend/tests/unit/src/services/api/alert.spec.ts
  frontend/tests/unit/src/services/api/base.spec.ts
  frontend/tests/unit/src/services/api/event.spec.ts
  frontend/tests/unit/src/store/filter.spec.ts
  frontend/tests/unit/src/store/helpers.spec.ts
  gui_api/app/api/routes/alert.py
  gui_api/app/api/routes/event.py
Labels: enhancement, gui, api

#270 Disposition History Tags
  frontend/src/components/Alerts/AlertDispositionTag.vue
  frontend/src/components/Alerts/AlertTableExpansion.vue
  frontend/src/components/Observables/ObservableDispositionHistoryGroup.vue
  frontend/src/components/Observables/ObservableLeaf.vue
  frontend/tests/component/src/components/Alerts/AlertDispositionTag.spec.ts
  frontend/tests/component/src/components/Alerts/AlertTableExpansion.spec.ts
  frontend/tests/component/src/components/Observables/ObservableDispositionHistoryGroup.spec.ts
  frontend/tests/component/src/components/Observables/ObservableLeaf.spec.ts
  frontend/tests/e2e/specs/ViewAlert.spec.js
  frontend/tests/mocks/observable.ts
Labels: enhancement, gui

#271 DB/API - NOT filter logic
  db_api/app/api/routes/event.py
  db_api/app/api/routes/submission.py
  db_api/app/db/crud/event.py
  db_api/app/db/crud/submission.py
  db_api/app/tests/api_tests/event/test_read.py
  db_api/app/tests/api_tests/submission/test_read.py
  db_api/app/tests/db_tests/crud/event/test_read.py
  db_api/app/tests/db_tests/crud/submission/test_read.py
  db_api/app/tests/factory/submission.py
  frontend/tests/e2e/specs/ViewAlert.spec.js
  gui_api/app/api/routes/alert.py
  gui_api/app/api/routes/event.py
  gui_api/app/tests/api/alert/test_read.py
  gui_api/app/tests/api/event/test_read.py
Labels: enhancement, api, database

#275 NOT Filters GUI - Filter Store & API Services
  frontend/src/components/Alerts/AlertTableExpansion.vue
  frontend/src/components/Events/EventAlertsTable.vue
  frontend/src/components/Filters/FilterChip.vue
  frontend/src/components/Filters/TheFilterToolbar.vue
  frontend/src/components/Metadata/MetadataTag.vue
  frontend/src/components/Modals/FilterModal.vue
  frontend/src/components/Modals/SaveToEventModal.vue
  frontend/src/components/Node/NodeQueueSelector.vue
  frontend/src/components/Node/TheNodeTable.vue
  frontend/src/components/Observables/ObservableDispositionHistoryGroup.vue
  frontend/src/components/Observables/ObservableLeaf.vue
  frontend/src/components/UserInterface/DateRangePicker.vue
  frontend/src/etc/constants/alerts.ts
  frontend/src/etc/helpers.ts
  frontend/src/models/alert.ts
  frontend/src/models/event.ts
  frontend/src/stores/filter.ts
  frontend/src/stores/helpers.ts
  frontend/tests/component/src/components/Alerts/AlertTableExpansion.spec.ts
  frontend/tests/component/src/components/Filters/FilterChip.spec.ts
  frontend/tests/component/src/components/Filters/FilterChipContainer.spec.ts
  frontend/tests/component/src/components/Filters/TheFilterToolbar.spec.ts
  frontend/tests/component/src/components/Metadata/Tag.spec.ts
  frontend/tests/component/src/components/Modals/FilterModal.spec.ts
  frontend/tests/component/src/components/Modals/SaveToEventModal.spec.ts
  frontend/tests/component/src/components/Node/NodeQueueSelector.spec.ts
  frontend/tests/component/src/components/Node/TheNodeTable.spec.ts
  frontend/tests/component/src/components/Observables/ObservableDispositionHistoryGroup.spec.ts
  frontend/tests/component/src/components/Observables/ObservableLeaf.spec.ts
  frontend/tests/component/src/components/UserInterface/DateRangePicker.spec.ts
  frontend/tests/unit/src/etc/helpers.spec.ts
  frontend/tests/unit/src/services/api/alert.spec.ts
  frontend/tests/unit/src/services/api/event.spec.ts
  frontend/tests/unit/src/store/filter.spec.ts
  frontend/tests/unit/src/store/helpers.spec.ts
Labels: enhancement, gui

#277 NOT Filters - Filter Modal/Quick Add/Filter Chips
  frontend/src/components/Filters/FilterChip.vue
  frontend/src/components/Filters/TheFilterToolbar.vue
  frontend/src/components/Modals/FilterModal.vue
  frontend/src/components/Objects/ObjectPropertyInput.vue
  frontend/tests/component/src/components/Filters/FilterChip.spec.ts
  frontend/tests/component/src/components/Filters/TheFilterToolbar.spec.ts
  frontend/tests/component/src/components/Modals/FilterModal.spec.ts
  frontend/tests/e2e/specs/ManageAlerts.spec.js
Labels: enhancement, gui

#278 Update GUI filter links for 'NOT' filters
  frontend/src/etc/helpers.ts
  frontend/tests/unit/src/etc/helpers.spec.ts
Labels: enhancement, gui

#280 Adds matching event status information to observables
  api_models/observable.py
  db_api/app/db/crud/submission.py
  db_api/app/db/schemas/observable.py
  db_api/app/tests/db_tests/crud/submission/test_read.py
  frontend/src/models/observable.ts
  frontend/tests/mocks/observable.ts
Labels: enhancement, api

#282 Fix for renaming PrimeVue CSS classes
  db_api/app/tests/db_tests/crud/submission/test_read.py
  db_api/app/tests/factory/submission.py
  frontend/src/components/Alerts/AlertTree.vue
Labels: bug, gui

#283 Matching event tags
  frontend/src/components/Events/EventStatusTag.vue
  frontend/src/components/Observables/ObservableEventStatusGroup.vue
  frontend/src/components/Observables/ObservableLeaf.vue
  frontend/src/etc/configuration/events.ts
  frontend/src/etc/configuration/test/events.ts
  frontend/tests/component/src/components/Events/EventStatusTag.spec.ts
  frontend/tests/component/src/components/Observables/ObservableEventStatusGroup.spec.ts
Labels: enhancement, gui

#281 Convert AnalyzeAlertForm to TypeScript
  db_api/app/db/schemas/observable.py
  db_api/app/tests/db_tests/crud/submission/test_read.py
  frontend/src/components/Alerts/AnalyzeAlertForm.vue
  frontend/src/models/alert.ts
  frontend/src/models/base.ts
  frontend/src/models/observable.ts
  frontend/tests/component/src/components/Alerts/AnalyzeAlertForm.spec.ts
Labels: refactor, gui

#284 Backend - Matching events for alerts
  api_models/event.py
  api_models/observable.py
  api_models/submission.py
  db_api/app/db/crud/history.py
  db_api/app/db/crud/submission.py
  db_api/app/db/schemas/event.py
  db_api/app/db/schemas/metadata_tag.py
  db_api/app/db/schemas/submission.py
  db_api/app/tests/db_tests/crud/submission/test_read.py
  frontend/src/models/alert.ts
  frontend/src/models/event.ts
  frontend/src/models/observable.ts
  frontend/tests/mocks/alert.ts
  frontend/tests/mocks/dispositionHistory.ts
  frontend/tests/mocks/events.ts
Labels: enhancement, api, database

#285 Update dependencies
  frontend/cypress/support/component-index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Alerts/AnalyzeAlertForm.vue
  frontend/src/components/Filters/FilterChip.vue
  frontend/src/components/Objects/ObjectPropertyInput.vue
  frontend/src/components/Observables/NewObservableForm.vue
  frontend/src/components/Observables/ObservableLeaf.vue
  frontend/src/components/UserInterface/DateRangePicker.vue
  frontend/src/main.ts
  frontend/tests/component/src/components/Alerts/AnalyzeAlertForm.spec.ts
  frontend/tests/component/src/components/Events/EventSummary.spec.ts
  frontend/tests/component/src/components/Filters/TheFilterToolbar.spec.ts
  frontend/tests/component/src/components/Modals/DeleteModal.spec.ts
  frontend/tests/component/src/components/Modals/EditEventModal.spec.ts
  frontend/tests/component/src/components/Modals/RemediateModal.spec.ts
  frontend/tests/component/src/components/Objects/ObjectPropertyInput.spec.ts
  frontend/tests/component/src/components/UserInterface/DateRangePicker.spec.ts
  frontend/tests/e2e/specs/ManageAlerts.spec.js
  frontend/tests/e2e/specs/ManageEvents.spec.js
  frontend/tests/e2e/specs/TheEventsTable.spec.js
  frontend/tests/e2e/support/index-ct.js
  frontend/tests/unit/src/etc/helpers.spec.ts
  frontend/tests/unit/src/store/helpers.spec.ts
  frontend/tests/unitHelpers.ts
Labels: bug, refactor

#286 Updates the frontend dev container to match Cypress version
  frontend/Dockerfile.dev
Labels: enhancement

#290 Adds docs for VSCode extensions
  docs/development/index.md
Labels: documentation
