Repository ace-ecosystem/ace2-ams, pull requests merged in 2022-02, with the labels that each got.

#114 Decouples new Manage Events page E2E tests
  backend/app/api/models/test.py
  backend/app/api/routes/test.py
  backend/app/tests/api/test_auth.py
  backend/app/tests/api/test_test.py
  frontend/tests/e2e/specs/ManageEvents.spec.js
Labels: refactor, gui, api

#117 Manage Events row expansion
  backend/app/api/routes/test.py
  backend/app/insert-event.py
  bin/insert-alerts.sh
  bin/insert-event.sh
  bin/test-backend.sh
  bin/test-e2e.sh
  bin/test-frontend-unit.sh
  bin/test-interactive-e2e.sh
  frontend/src/components/Alerts/AlertTableCell.vue
  frontend/src/components/Alerts/AlertTableExpansion.vue
  frontend/src/components/Events/EventTableExpansion.vue
  frontend/src/components/Events/TheEventsTable.vue
  frontend/src/etc/constants.ts
  frontend/src/etc/helpers.ts
  frontend/src/services/api/alert.ts
  frontend/src/services/api/base.ts
  frontend/src/stores/alertTable.ts
  frontend/tests/e2e/specs/ManageEvents.spec.js
  frontend/tests/e2e/specs/TheEventsTable.spec.js
  frontend/tests/mocks/alert.ts
  frontend/tests/unit/src/components/Alerts/AlertTableCell.spec.ts
  frontend/tests/unit/src/components/Events/EventTableExpansion.spec.ts
  frontend/tests/unit/src/store/alertTable.spec.ts
Labels: enhancement, gui

#118 Adds executable permission
  bin/disable-test-mode.sh
  bin/enable-test-mode.sh
Labels: bug

#119 Alert Details Table
  frontend/src/components/Alerts/AlertTableCell.vue
  frontend/src/components/Alerts/TheAlertDetails.vue
  frontend/src/components/Events/EventTableCell.vue
  frontend/src/components/Node/NodeComment.vue
  frontend/src/etc/helpers.ts
  frontend/src/models/alert.ts
  frontend/src/pages/Alerts/ViewAlert.vue
  frontend/src/stores/alert.ts
  frontend/tests/e2e/specs/ViewAlert.spec.js
  frontend/tests/mocks/alert.ts
  frontend/tests/unit/src/components/Alerts/AlertTableCell.spec.ts
  frontend/tests/unit/src/components/Alerts/TheAlertDetails.spec.ts
  frontend/tests/unit/src/components/Events/EventTableCell.spec.ts
  frontend/tests/unit/src/components/Node/NodeComment.spec.ts
  frontend/tests/unit/src/etc/helpers.spec.ts
  frontend/tests/unit/src/store/alert.spec.ts
  frontend/tests/unit/src/store/alertTable.spec.ts
Labels: enhancement, gui

#121 Add Alerts to Event / Save to Event Modal
  backend/app/api/models/test.py
  backend/app/api/routes/test.py
  backend/app/tests/api/test_test.py
  frontend/src/components/Events/EventTableExpansion.vue
  frontend/src/components/Modals/BaseModal.vue
  frontend/src/components/Modals/DispositionModal.vue
  frontend/src/components/Modals/SaveToEventModal.vue
  frontend/src/models/event.ts
  frontend/src/services/api/event.ts
  frontend/src/stores/eventTable.ts
  frontend/tests/e2e/specs/ManageAlerts.spec.js
  frontend/tests/e2e/specs/TheEventsTable.spec.js
  frontend/tests/mocks/events.ts
  frontend/tests/mocks/user.ts
  frontend/tests/unit/src/components/Modals/DispositionModal.spec.ts
  frontend/tests/unit/src/components/Modals/SaveToEventModal.spec.ts
  frontend/tests/unit/src/services/api/event.spec.ts
Labels: enhancement, gui, api

#122 Fix multiple API calls when row in TheAlertsTable/TheEventsTable expanded
  frontend/src/components/Alerts/AlertTableExpansion.vue
  frontend/src/components/Alerts/TheAlertsTable.vue
  frontend/src/components/Events/EventTableExpansion.vue
  frontend/src/components/Events/TheEventsTable.vue
  frontend/src/etc/helpers.ts
  frontend/tests/unit/src/components/Alerts/AlertTableExpansion.spec.ts
  frontend/tests/unit/src/components/Alerts/TheAlertsTable.spec.ts
  frontend/tests/unit/src/components/Events/EventTableExpansion.spec.ts
  frontend/tests/unit/src/components/Events/TheEventsTable.spec.ts
Labels: bug, gui

#126 Calculate event times
  backend/app/api/models/event.py
  backend/app/api/models/history.py
  backend/app/api/routes/alert.py
  backend/app/api/routes/auth.py
  backend/app/api/routes/event.py
  backend/app/api/routes/node_comment.py
  backend/app/api/routes/observable.py
  backend/app/api/routes/user.py
  backend/app/core/auth.py
  backend/app/db/crud/__init__.py
  backend/app/db/migrations/versions/7ac462762562_initial.py
  backend/app/db/schemas/alert.py
  backend/app/db/schemas/event.py
  backend/app/db/schemas/history.py
  backend/app/db/schemas/node.py
  backend/app/db/schemas/observable.py
  backend/app/db/schemas/user.py
  backend/app/tests/api/alert/test_create.py
  backend/app/tests/api/alert/test_read.py
  backend/app/tests/api/alert/test_update.py
  backend/app/tests/api/alert_queue/test_read.py
  backend/app/tests/api/event/test_create.py
  backend/app/tests/api/event/test_read.py
  backend/app/tests/api/event/test_update.py
  backend/app/tests/api/event_queue/test_read.py
  backend/app/tests/api/node_comment/test_create.py
  backend/app/tests/api/node_comment/test_delete.py
  backend/app/tests/api/node_comment/test_update.py
  backend/app/tests/api/observable/test_create.py
  backend/app/tests/api/observable/test_update.py
  backend/app/tests/api/test_auth.py
  backend/app/tests/api/test_auth_refresh.py
  backend/app/tests/api/test_auth_validate.py
  backend/app/tests/api/user/test_create.py
  backend/app/tests/api/user/test_read.py
  backend/app/tests/api/user/test_update.py
  backend/app/tests/api/user_role/test_delete.py
  backend/app/tests/api/user_role/test_read.py
  backend/app/tests/conftest.py
  backend/app/tests/helpers.py
  frontend/src/models/event.ts
  frontend/src/models/history.ts
  frontend/src/models/node.ts
  frontend/src/models/page.ts
  frontend/src/services/api/alert.ts
  frontend/src/services/api/event.ts
  frontend/src/services/api/observable.ts
  frontend/src/services/api/observableInstance.ts
  frontend/src/services/api/user.ts
  frontend/tests/mocks/events.ts
Labels: enhancement, gui, api

#127 Edit Event Modal
  frontend/src/components/Alerts/TheAlertsTable.vue
  frontend/src/components/Events/EventTableCell.vue
  frontend/src/components/Events/TheEventsTable.vue
  frontend/src/components/Filters/FilterChip.vue
  frontend/src/components/Filters/TheFilterToolbar.vue
  frontend/src/components/Modals/EditEventModal.vue
  frontend/src/components/Modals/FilterModal.vue
  frontend/src/components/Node/NodeCommentEditor.vue
  frontend/src/components/Node/NodePropertyInput.vue
  frontend/src/components/Node/NodeThreatSelector.vue
  frontend/src/components/Node/TheNodeTable.vue
  frontend/src/etc/constants.ts
  frontend/src/etc/helpers.ts
  frontend/src/pages/Alerts/ManageAlerts.vue
  frontend/src/pages/Events/ManageEvents.vue
  frontend/src/services/api/eventRemediation.ts
  frontend/src/services/api/nodeThreatType.ts
  frontend/src/stores/eventRemediation.ts
  frontend/src/stores/nodeThreat.ts
  frontend/src/stores/nodeThreatType.ts
  frontend/tests/e2e/specs/ManageEvents.spec.js
  frontend/tests/e2e/specs/TheEventsTable.spec.js
  frontend/tests/mocks/events.ts
  frontend/tests/unit/src/components/Alerts/TheAlertsTable.spec.ts
  frontend/tests/unit/src/components/Events/EventTableCell.spec.ts
  frontend/tests/unit/src/components/Events/TheEventsTable.spec.ts
  frontend/tests/unit/src/components/Filters/FilterChip.spec.ts
  frontend/tests/unit/src/components/Filters/TheFilterToolbar.spec.ts
  frontend/tests/unit/src/components/Modals/EditEventModal.spec.ts
  frontend/tests/unit/src/components/Modals/FilterModal.spec.ts
  frontend/tests/unit/src/components/Node/NodeCommentEditor.spec.ts
  frontend/tests/unit/src/components/Node/NodePropertyInput.spec.ts
  frontend/tests/unit/src/components/Node/NodeThreatSelector.spec.ts
  frontend/tests/unit/src/components/Node/TheNodeTable.spec.ts
Labels: gui

#131 Downgrades v-calendar to fix bug
  frontend/package-lock.json
  frontend/package.json
Labels: bug, gui

#133 Check for .only frontend test restrictions
  .github/workflows/main.yml
  bin/frontend-check-for-only.sh
Labels: enhancement, gui

#134 Add inital 'queue' support and re-organize constants/config
  backend/app/etc/defaults.yml
  backend/app/seed.py
  docker-compose.yml
  frontend/src/App.vue
  frontend/src/components/Events/TheEventsTable.vue
  frontend/src/components/Filters/FilterChip.vue
  frontend/src/components/Filters/TheFilterToolbar.vue
  frontend/src/components/Modals/EditEventModal.vue
  frontend/src/components/Node/TheNodeTable.vue
  frontend/src/etc/configuration/alerts.ts
  frontend/src/etc/configuration/events.ts
  frontend/src/etc/configuration/index.ts
  frontend/src/etc/configuration/test/alerts.ts
  frontend/src/etc/configuration/test/events.ts
  frontend/src/etc/configuration/test/index.ts
  frontend/src/etc/constants.ts
  frontend/src/etc/constants/alerts.ts
  frontend/src/etc/constants/base.ts
  frontend/src/etc/constants/events.ts
  frontend/src/etc/helpers.ts
  frontend/src/etc/validators.ts
  frontend/src/models/base.ts
  frontend/src/pages/Alerts/ManageAlerts.vue
  frontend/src/pages/Events/ManageEvents.vue
  frontend/src/pages/User/TheLogin.vue
  frontend/src/services/api/alert.ts
  frontend/src/services/api/event.ts
  frontend/src/stores/currentUserSettings.ts
  frontend/src/stores/filter.ts
  frontend/tests/e2e/specs/ManageAlerts.spec.js
  frontend/tests/e2e/specs/ManageEvents.spec.js
  frontend/tests/e2e/specs/TheAlertsTable.spec.js
  frontend/tests/e2e/specs/TheEventsTable.spec.js
  frontend/tests/e2e/specs/ViewAnalysis.spec.js
  frontend/tests/e2e/support/commands.js
  frontend/tests/unit/src/components/Events/TheEventsTable.spec.ts
  frontend/tests/unit/src/components/Filters/FilterChip.spec.ts
  frontend/tests/unit/src/components/Filters/TheFilterToolbar.spec.ts
  frontend/tests/unit/src/components/Modals/EditEventModal.spec.ts
  frontend/tests/unit/src/components/Node/NodePropertyInput.spec.ts
  frontend/tests/unit/src/etc/helpers.spec.ts
  frontend/tests/unit/src/pages/Alerts/ManageAlerts.spec.ts
  frontend/tests/unit/src/pages/Events/ManageEvents.spec.ts
Labels: enhancement, refactor, gui, api

#136 Associate items with queues in backend seed script
  backend/app/etc/defaults.yml
  backend/app/seed.py
  backend/app/tests/api/alert/test_update.py
  backend/app/tests/api/event/test_create.py
  backend/app/tests/api/event/test_update.py
  backend/app/tests/helpers.py
  bin/test-backend.sh
  bin/test-e2e.sh
  bin/test-frontend-unit.sh
  bin/test-interactive-e2e.sh
  frontend/src/components/Alerts/AnalyzeAlertForm.vue
  frontend/src/components/Node/NodeThreatSelector.vue
  frontend/src/etc/configuration/events.ts
  frontend/src/etc/configuration/test/alerts.ts
  frontend/src/etc/configuration/test/events.ts
  frontend/tests/e2e/specs/ManageAlerts.spec.js
  frontend/tests/e2e/specs/ManageEvents.spec.js
  frontend/tests/e2e/specs/TheEventsTable.spec.js
  frontend/tests/e2e/specs/ViewAlert.spec.js
  frontend/tests/e2e/specs/ViewAnalysis.spec.js
  frontend/tests/mocks/alert.ts
  frontend/tests/unit/src/components/Alerts/AlertTableCell.spec.ts
  frontend/tests/unit/src/components/Alerts/AnalyzeAlertForm.spec.ts
  frontend/tests/unit/src/components/Events/TheEventsTable.spec.ts
  frontend/tests/unit/src/components/Node/NodeThreatSelector.spec.ts
  frontend/tests/unit/src/store/alertTable.spec.ts
Labels: bug, api
