Repository ace-ecosystem/ace2-ams, pull requests merged in 2022-03, with the labels that each got.

#137 Add 'Queue' Logic to Filtering and Edit Event Modal
  backend/app/api/models/test.py
  backend/app/api/routes/test.py
  backend/app/etc/defaults.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Alerts/AnalyzeAlertForm.vue
  frontend/src/components/Events/TheEventsTable.vue
  frontend/src/components/Filters/FilterChip.vue
  frontend/src/components/Filters/TheFilterToolbar.vue
  frontend/src/components/Modals/EditEventModal.vue
  frontend/src/components/Modals/FilterModal.vue
  frontend/src/components/Node/NodePropertyInput.vue
  frontend/src/components/Node/NodeQueueSelector.vue
  frontend/src/etc/configuration/alerts.ts
  frontend/src/etc/configuration/events.ts
  frontend/src/etc/configuration/test/alerts.ts
  frontend/src/etc/configuration/test/events.ts
  frontend/src/etc/constants/alerts.ts
  frontend/src/etc/constants/base.ts
  frontend/src/etc/constants/events.ts
  frontend/src/etc/helpers.ts
  frontend/src/models/base.ts
  frontend/src/models/event.ts
  frontend/src/pages/Alerts/ManageAlerts.vue
  frontend/src/pages/Events/ManageEvents.vue
  frontend/src/services/api/alert.ts
  frontend/src/services/api/event.ts
  frontend/src/stores/currentUserSettings.ts
  frontend/src/stores/eventPreventionTool.ts
  frontend/src/stores/eventRemediation.ts
  frontend/src/stores/eventRiskLevel.ts
  frontend/src/stores/eventSource.ts
  frontend/src/stores/eventStatus.ts
  frontend/src/stores/eventTable.ts
  frontend/src/stores/eventType.ts
  frontend/src/stores/eventVector.ts
  frontend/src/stores/nodeThreat.ts
  frontend/src/stores/nodeThreatActor.ts
  frontend/tests/component/src/components/Modals/EditEventModal.spec.ts
  frontend/tests/e2e/plugins/index.js
  frontend/tests/e2e/specs/ManageAlerts.spec.js
  frontend/tests/e2e/specs/ManageEvents.spec.js
  frontend/tests/e2e/specs/TheEventsTable.spec.js
  frontend/tests/e2e/specs/ViewAlert.spec.js
  frontend/tests/e2e/specs/helpers.js
  frontend/tests/mocks/events.ts
  frontend/tests/unit/src/components/Alerts/AnalyzeAlertForm.spec.ts
  frontend/tests/unit/src/components/Events/TheEventsTable.spec.ts
  frontend/tests/unit/src/components/Filters/FilterChip.spec.ts
  frontend/tests/unit/src/components/Filters/TheFilterToolbar.spec.ts
  frontend/tests/unit/src/components/Modals/EditEventModal.spec.ts
  frontend/tests/unit/src/components/Modals/FilterModal.spec.ts
  frontend/tests/unit/src/components/Modals/SaveToEventModal.spec.ts
  frontend/tests/unit/src/components/Node/NodePropertyInput.spec.ts
  frontend/tests/unit/src/components/Node/NodeQueueSelector.spec.ts
  frontend/tests/unit/src/etc/helpers.spec.ts
  frontend/tests/unit/src/pages/Alerts/ManageAlerts.spec.ts
  frontend/tests/unit/src/pages/Events/ManageEvents.spec.ts
  frontend/tests/unit/src/store/eventTable.spec.ts
Labels: enhancement, gui, api

#139 Fix overwriting tags bug
  frontend/src/components/Alerts/AlertTree.vue
  frontend/src/components/Alerts/AnalyzeAlertForm.vue
  frontend/src/components/Alerts/TheAlertDetails.vue
  frontend/src/components/Modals/TagModal.vue
  frontend/src/components/Node/TheNodeActionToolbar.vue
  frontend/src/pages/Alerts/ViewAlert.vue
  frontend/src/pages/Alerts/ViewAnalysis.vue
  frontend/src/stores/alert.ts
  frontend/src/stores/event.ts
  frontend/tests/e2e/specs/ViewAlert.spec.js
  frontend/tests/unit/src/components/Alerts/AlertTree.spec.ts
  frontend/tests/unit/src/components/Modals/TagModal.spec.ts
  frontend/tests/unit/src/pages/Alerts/ViewAlert.spec.ts
  frontend/tests/unit/src/pages/Alerts/ViewAnalysis.spec.ts
  frontend/tests/unit/src/store/alert.spec.ts
  frontend/tests/unit/src/store/event.spec.ts
Labels: bug, gui

#140 Adds dummy analysis details
  backend/app/tests/alerts/small.json
  backend/app/tests/alerts/small_template.json
  backend/app/tests/helpers.py
  bin/insert-alerts.sh
  bin/insert-event.sh
Labels: enhancement, api

#141 Event Details Menu
  frontend/src/components/Analysis/AnalysisDetailsBase.vue
  frontend/src/components/Events/EventSummary.vue
  frontend/src/components/Events/TheEventDetailsMenuBar.vue
  frontend/src/etc/configuration/analysis.ts
  frontend/src/etc/configuration/index.ts
  frontend/src/etc/configuration/test/analysis.ts
  frontend/src/etc/configuration/test/index.ts
  frontend/src/etc/constants/events.ts
  frontend/src/pages/Events/ViewEvent.vue
  frontend/src/router/index.ts
  frontend/tests/e2e/specs/ViewEvent.spec.js
  frontend/tests/e2e/support/commands.js
  frontend/tests/unit/src/components/Events/TheEventDetailsMenuBar.spec.ts
  frontend/tests/unit/src/pages/Events/ViewEvent.spec.ts
Labels: enhancement, gui

#145 API endpoint for event observable summary
  backend/app/api/models/event_summaries.py
  backend/app/api/routes/event.py
  backend/app/api/routes/event_summaries.py
  backend/app/db/migrations/versions/9dac6f40a0d3_initial.py
  backend/app/db/schemas/analysis_module_type.py
  backend/app/tests/alerts/small.json
  backend/app/tests/alerts/small_template.json
  backend/app/tests/api/alert/test_read.py
  backend/app/tests/api/event/test_read.py
  frontend/src/models/eventSummaries.ts
  frontend/tests/e2e/specs/ViewAlert.spec.js
Labels: enhancement, api

#144 Event Details URL Summary
  backend/app/etc/defaults.yml
  backend/app/tests/alerts/smallWithUrls.json
  frontend/src/components/Analysis/AnalysisDetailsBase.vue
  frontend/src/components/Events/EventURLSummary.vue
  frontend/src/etc/constants/events.ts
  frontend/src/pages/Events/ViewEvent.vue
  frontend/tests/e2e/specs/AnalyzeAlert.spec.js
  frontend/tests/e2e/specs/ViewEvent.spec.js
  frontend/tests/mocks/observable.ts
  frontend/tests/unit/src/components/Events/EventURLSummary.spec.ts
Labels: enhancement, gui

#146 Tweak for Observable Summary API endpoint
  backend/app/api/models/event_summaries.py
  backend/app/api/routes/event_summaries.py
  backend/app/tests/api/event/test_read.py
  frontend/src/models/eventSummaries.ts
Labels: bug, api

#148 Reorganizes some E2E tests
  backend/app/db/migrations/versions/f04f3d2ce9fc_initial.py
  backend/app/db/schemas/__init__.py
  backend/app/db/schemas/seed.py
  backend/app/etc/defaults.yml
  backend/app/seed.py
  frontend/tests/e2e/specs/ManageAlerts.spec.js
  frontend/tests/e2e/specs/ViewAlert.spec.js
Labels: refactor, gui, api

#152 API - event user summary
  backend/app/api/models/event_summaries.py
  backend/app/api/routes/event.py
  backend/app/api/routes/event_summaries.py
  backend/app/tests/alerts/smallWithUsers.json
  backend/app/tests/api/event/test_read.py
  frontend/src/models/eventSummaries.ts
Labels: enhancement, gui, api

#153 Add event observable summary tags column
  frontend/src/components/Events/EventObservableSummary.vue
  frontend/src/components/Node/NodeTag.vue
  frontend/tests/e2e/specs/ViewEvent.spec.js
Labels: bug, gui

#154 Changes Save to Event modal's comment functionality
  backend/app/tests/alerts/smallWithUrls.json
  frontend/src/components/Modals/SaveToEventModal.vue
  frontend/tests/e2e/specs/ManageAlerts.spec.js
Labels: enhancement, gui

#155 Fixes Manage Events page automatically fetching every displayed event
  frontend/src/components/Events/EventTableCell.vue
  frontend/src/components/Modals/EditEventModal.vue
Labels: bug, gui

#156 Event URL Domain summary API endpoint
  backend/app/api/models/event_summaries.py
  backend/app/api/routes/event.py
  backend/app/api/routes/event_summaries.py
  backend/app/tests/api/event/test_read.py
  frontend/src/models/eventSummaries.ts
Labels: enhancement, gui, api

#157 Event Details - User Analysis Section
  frontend/src/components/Analysis/UserAnalysis.vue
  frontend/src/etc/configuration/analysis.ts
  frontend/src/etc/configuration/test/analysis.ts
  frontend/src/services/api/event.ts
  frontend/tests/e2e/specs/ViewEvent.spec.js
  frontend/tests/unit/src/services/api/event.spec.ts
Labels: enhancement, gui

#158 Event Details - URL Domain Summary Section
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Events/EventURLDomainSummary.vue
  frontend/src/components/Events/TheEventDetailsMenuBar.vue
  frontend/src/etc/constants/events.ts
  frontend/src/services/api/event.ts
  frontend/tests/e2e/specs/ViewEvent.spec.js
  frontend/tests/unit/src/services/api/event.spec.ts
Labels: enhancement, gui

#159 Event email summary API endpoint
  backend/app/api/models/analysis.py
  backend/app/api/models/analysis_details.py
  backend/app/api/models/event_summaries.py
  backend/app/api/routes/analysis.py
  backend/app/api/routes/event.py
  backend/app/api/routes/event_summaries.py
  backend/app/tests/api/analysis/test_create.py
  backend/app/tests/api/event/test_read.py
  backend/requirements.txt
  frontend/src/models/eventSummaries.ts
Labels: enhancement, gui, api

#160 Bugfix - Multiple Manage Alerts Calls
  frontend/src/App.vue
  frontend/src/components/Events/TheEventsTable.vue
  frontend/src/components/Node/NodeQueueSelector.vue
  frontend/src/components/Node/NodeTag.vue
  frontend/src/components/Node/TheNodeTable.vue
  frontend/src/etc/helpers.ts
  frontend/src/pages/Alerts/ManageAlerts.vue
  frontend/src/pages/Events/ManageEvents.vue
  frontend/src/services/api/alert.ts
  frontend/src/stores/alertTable.ts
  frontend/src/stores/eventTable.ts
  frontend/tests/e2e/specs/ManageAlerts.spec.js
  frontend/tests/e2e/specs/ManageEvents.spec.js
  frontend/tests/e2e/specs/TheAlertsTable.spec.js
  frontend/tests/e2e/specs/TheEventsTable.spec.js
  frontend/tests/e2e/specs/ViewAnalysis.spec.js
  frontend/tests/unit/src/App.spec.ts
  frontend/tests/unit/src/etc/helpers.spec.ts
  frontend/tests/unit/src/services/api/alert.spec.ts
  frontend/tests/unit/src/store/alert.spec.ts
  frontend/tests/unit/src/store/alertTable.spec.ts
  frontend/tests/unit/src/store/eventTable.spec.ts
Labels: bug, gui

#161 Adds API endpoint for fetching an event's email headers/body summary
  backend/app/api/models/analysis_details.py
  backend/app/api/models/event_summaries.py
  backend/app/api/routes/event.py
  backend/app/api/routes/event_summaries.py
  backend/app/tests/api/event/test_read.py
  frontend/src/models/eventSummaries.ts
Labels: enhancement, gui, api

#162 Event Details - Email Analysis
  backend/app/tests/alerts/small.json
  backend/app/tests/alerts/smallWithUrls.json
  backend/app/tests/alerts/smallWithUsers.json
  backend/app/tests/alerts/small_template.json
  frontend/src/components/Analysis/EmailAnalysis.vue
  frontend/src/etc/configuration/analysis.ts
  frontend/src/etc/configuration/test/analysis.ts
  frontend/src/services/api/event.ts
  frontend/tests/e2e/specs/ViewEvent.spec.js
  frontend/tests/unit/src/services/api/event.spec.ts
Labels: enhancement, gui

#163 Event details - Email Analysis - Headers & Body
  backend/app/tests/alerts/smallWithHeadersBody.json
  frontend/src/components/Analysis/EmailAnalysis.vue
  frontend/src/components/Analysis/EmailAnalysisHeadersBody.vue
  frontend/src/components/Analysis/EmailAnalysisSummaryTable.vue
  frontend/src/models/eventSummaries.ts
  frontend/src/services/api/event.ts
  frontend/tests/e2e/specs/ViewEvent.spec.js
  frontend/tests/unit/src/services/api/event.spec.ts
Labels: enhancement, gui

#164 Node detection points
  backend/app/api/models/analysis.py
  backend/app/api/models/node_detection_point.py
  backend/app/api/models/observable.py
  backend/app/api/routes/__init__.py
  backend/app/api/routes/node.py
  backend/app/api/routes/node_comment.py
  backend/app/api/routes/node_detection_point.py
  backend/app/db/crud/__init__.py
  backend/app/db/migrations/versions/ff77f773ba60_initial.py
  backend/app/db/schemas/__init__.py
  backend/app/db/schemas/node.py
  backend/app/db/schemas/node_detection_point.py
  backend/app/tests/api/node_detection_point/__init__.py
  backend/app/tests/api/node_detection_point/test_create.py
  backend/app/tests/api/node_detection_point/test_delete.py
  backend/app/tests/api/node_detection_point/test_read.py
  backend/app/tests/api/node_detection_point/test_update.py
  backend/app/tests/helpers.py
  frontend/src/models/nodeDetectionPoint.ts
  frontend/src/services/api/nodeDetectionPoint.ts
Labels: enhancement, gui, api

#165 Event detection point summary API endpoint
  backend/app/api/models/event_summaries.py
  backend/app/api/routes/event.py
  backend/app/api/routes/event_summaries.py
  backend/app/tests/api/event/test_read.py
  frontend/src/models/eventSummaries.ts
Labels: enhancement, gui, api

#166 Event Details - Detection Summary Section
  frontend/src/components/Events/EventDetectionsSummary.vue
  frontend/src/components/Events/TheEventDetailsMenuBar.vue
  frontend/src/etc/constants/events.ts
  frontend/src/services/api/event.ts
  frontend/tests/e2e/specs/ViewEvent.spec.js
  frontend/tests/unit/src/services/api/event.spec.ts
Labels: enhancement, gui

#167 Node relationships
  backend/app/api/models/alert.py
  backend/app/api/models/event.py
  backend/app/api/models/history.py
  backend/app/api/models/node_relationship.py
  backend/app/api/models/node_relationship_type.py
  backend/app/api/models/observable.py
  backend/app/api/routes/__init__.py
  backend/app/api/routes/alert.py
  backend/app/api/routes/event.py
  backend/app/api/routes/node.py
  backend/app/api/routes/node_comment.py
  backend/app/api/routes/node_detection_point.py
  backend/app/api/routes/node_relationship.py
  backend/app/api/routes/node_relationship_type.py
  backend/app/api/routes/observable.py
  backend/app/api/routes/user.py
  backend/app/db/crud/__init__.py
  backend/app/db/migrations/versions/2d952cc05bfc_initial.py
  backend/app/db/schemas/__init__.py
  backend/app/db/schemas/alert.py
  backend/app/db/schemas/event.py
  backend/app/db/schemas/history.py
  backend/app/db/schemas/node.py
  backend/app/db/schemas/node_relationship.py
  backend/app/db/schemas/node_relationship_type.py
  backend/app/db/schemas/observable.py
  backend/app/db/schemas/user.py
  backend/app/etc/defaults.yml
  backend/app/seed.py
  backend/app/tests/api/event/test_read.py
  backend/app/tests/api/event/test_update.py
  backend/app/tests/api/node_comment/test_create.py
  backend/app/tests/api/node_comment/test_delete.py
  backend/app/tests/api/node_comment/test_update.py
  backend/app/tests/api/node_detection_point/test_create.py
  backend/app/tests/api/node_detection_point/test_delete.py
  backend/app/tests/api/node_detection_point/test_update.py
  backend/app/tests/api/node_relationship/__init__.py
  backend/app/tests/api/node_relationship/test_create.py
  backend/app/tests/api/node_relationship/test_delete.py
  backend/app/tests/api/node_relationship/test_read.py
  backend/app/tests/api/node_relationship_type/__init__.py
  backend/app/tests/api/node_relationship_type/test_create.py
  backend/app/tests/api/node_relationship_type/test_delete.py
  backend/app/tests/api/node_relationship_type/test_read.py
  backend/app/tests/api/node_relationship_type/test_update.py
  backend/app/tests/api/observable/test_read.py
  backend/app/tests/helpers.py
  frontend/src/models/nodeRelationship.ts
  frontend/src/models/nodeRelationshipType.ts
  frontend/src/models/observable.ts
Labels: enhancement, gui, api

#169 Relationship column in Observable Summary table
  backend/app/tests/alerts/smallWithUrls.json
  backend/app/tests/helpers.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Events/EventObservableSummary.vue
  frontend/src/components/Node/NodeRelationship.vue
  frontend/tests/component/src/components/Node/NodeRelationship.spec.ts
  frontend/tests/e2e/specs/ViewEvent.spec.js
Labels: enhancement, gui

#170 Clean up frontend imports and more
  frontend/src/components/Alerts/TheAlertDetails.vue
  frontend/src/components/Events/EventAlertsTable.vue
  frontend/src/components/Events/EventTableCell.vue
  frontend/src/components/Filters/FilterChip.vue
  frontend/src/components/Filters/TheFilterToolbar.vue
  frontend/src/components/Modals/EditEventModal.vue
  frontend/src/components/Modals/FilterModal.vue
  frontend/src/components/Node/NodeCommentEditor.vue
  frontend/src/etc/configuration/alerts.ts
  frontend/src/etc/constants/events.ts
  frontend/src/stores/nodeThreat.ts
  frontend/tests/component/src/components/Alerts/AlertTableExpansion.spec.ts
  frontend/tests/component/src/components/Events/EventAlertsTable.spec.ts
  frontend/tests/component/src/components/Events/EventURLSummary.spec.ts
  frontend/tests/component/src/components/Modals/EditEventModal.spec.ts
  frontend/tests/component/src/components/Modals/TagModal.spec.ts
  frontend/tests/component/src/components/Node/NodeComment.spec.ts
  frontend/tests/component/src/components/Node/NodeCommentEditor.spec.ts
  frontend/tests/component/src/components/Node/NodeThreatSelector.spec.ts
  frontend/tests/component/src/components/Node/TheNodeActionToolbar.spec.ts
  frontend/tests/mocks/alert.ts
  frontend/tests/mocks/analysis.ts
  frontend/tests/mocks/observable.ts
  frontend/tests/unit/src/App.spec.ts.old
  frontend/tests/unit/src/etc/helpers.spec.ts
  frontend/tests/unit/src/services/api/alert.spec.ts
  frontend/tests/unit/src/services/api/analysis.spec.ts
  frontend/tests/unit/src/services/api/auth.spec.ts
  frontend/tests/unit/src/services/api/axios.spec.ts
  frontend/tests/unit/src/services/api/base.spec.ts
  frontend/tests/unit/src/services/api/event.spec.ts
  frontend/tests/unit/src/services/api/nodeComment.spec.ts
  frontend/tests/unit/src/services/api/nodeTree.spec.ts
  frontend/tests/unit/src/services/api/queue.spec.ts
  frontend/tests/unit/src/store/alert.spec.ts
  frontend/tests/unit/src/store/alertTable.spec.ts
  frontend/tests/unit/src/store/auth.spec.ts
  frontend/tests/unit/src/store/event.spec.ts
  frontend/tests/unit/src/store/eventTable.spec.ts
  frontend/tests/unit/src/store/filter.spec.ts
  frontend/tests/unit/src/store/helpers.spec.ts
  frontend/tests/unit/src/store/modal.spec.ts
  frontend/tests/unit/src/store/selectedAlert.spec.ts
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: refactor, gui

#173 Component tests
  .github/workflows/main.yml
  bin/test-components.sh
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Alerts/AlertTableCell.vue
  frontend/src/components/Alerts/AlertTableExpansion.vue
  frontend/src/components/Alerts/AlertTree.vue
  frontend/src/components/Alerts/AnalyzeAlertForm.vue
  frontend/src/etc/helpers.ts
  frontend/src/models/observable.ts
  frontend/src/pages/Alerts/ViewAlert.vue
  frontend/tests/component/src/App.spec.ts
  frontend/tests/component/src/components/Alerts/AlertTableCell.spec.ts
  frontend/tests/component/src/components/Alerts/AlertTableExpansion.spec.ts
  frontend/tests/component/src/components/Alerts/AlertTree.spec.ts
  frontend/tests/component/src/components/Alerts/AnalyzeAlertForm.spec.ts
  frontend/tests/component/src/pages/Alerts/AnalyzeAlert.spec.ts
  frontend/tests/component/src/pages/Alerts/ManageAlerts.spec.ts
  frontend/tests/component/src/pages/Alerts/ViewAlert.spec.ts
  frontend/tests/component/src/pages/Alerts/ViewAnalysis.spec.ts
  frontend/tests/component/src/pages/Events/ManageEvents.spec.ts
  frontend/tests/component/src/pages/Events/ViewEvent.spec.ts
  frontend/tests/component/src/pages/User/TheLogin.spec.ts
  frontend/tests/cypressHelpers.ts
  frontend/tests/e2e/support/commands.js
  frontend/tests/mocks/alert.ts
  frontend/tests/mocks/analysis.ts
  frontend/tests/mocks/observable.ts
  frontend/tests/unit/src/components/Alerts/AlertTableCell.spec.ts.old
  frontend/tests/unit/src/components/Alerts/AlertTableExpansion.spec.ts.old
  frontend/tests/unit/src/components/Alerts/AlertTree.spec.ts.old
  frontend/tsconfig.json
Labels: refactor

#175 Filter by clicking in node table
  frontend/src/components/Node/TheNodeTable.vue
  frontend/tests/e2e/specs/ManageAlerts.spec.js
  frontend/tests/e2e/specs/ManageEvents.spec.js
  frontend/tests/e2e/specs/TheEventsTable.spec.js
Labels: enhancement, gui
